### PR TITLE
NewRequests(farming coffee p)

### PR DESCRIPTION
**Pull request by starli2003**
here

### CODE REVIEW

**Comment by starli2003** [comment]
farmer table
farmer values

**Comment by Paccy-I** [comment]
what about adding in more data 
atleast to 10

**Comment by starli2003** [comment]
ok

**Comment by desireishimwe** [comment]
that  is okay 👌  thank you for your contribution

**Comment by starli2003** [comment]
Screenshot 2024-11-21 175436

**Comment by starli2003** [comment]
here is inner join

**Pull request closed without merging**
